### ISSUE TITLE
[Feature] "Already read" action marker

### ISSUE THREAD

**Issue by Steffo99** [Cookie-CHR/ASCII-quest#10]
Many adventure games change the color of choices that can be repeated and you've already read.
It would be nice to have the same in ASCII Quest!

<details>
<summary>Extremely minor, out of context spoilers for The Witcher 3</summary>

The Witcher 3 uses three colors for dialogue choices:
- yellow, for choices which permanently advance the conversation
- brown, for choices that do not advance the conversation and usually tell you more about the story
- grey, for repeatable choices you've already taken

![An example dialogue with six choices, two yellow, three brown, and one grey.](https://user-images.githubusercontent.com/1540885/187553864-df18909e-63cd-4f10-9c05-6a5768b2b64f.png "An example dialogue with six choices, two yellow, three brown, and one grey.")

</details>

**Comment by Cookie-CHR** [comment]
Made a patch, it only works in some occasions (and I'm still not sure what choices I should gray out and what I should leave as it is), but better than nothing

**Comment by Cookie-CHR** [comment]
I eventually decided that a missing feature is better than a broken one, and removed the buggy action marker I previously made

**Comment by Steffo99** [comment]
wise choice
