### ISSUE TITLE
[Feature] Save states

### ISSUE THREAD

**Issue by Steffo99** [Cookie-CHR/ASCII-quest#2]
Even if the game is pretty short, being able to save and reload progress at certain points may be useful, even if it may be considered a cheat. Perhaps only after achieving the *Good Ending*?

**Comment by Cookie-CHR** [comment]
I'm still not sure how to implement this feature, but I'll think about it

**Comment by Cookie-CHR** [comment]
Unfortunately, saving is quite hard for web games, I would have to mess with cookies and such. :(

Unless you talked about a "soft save" that is not inter-session but only relative to the single match, so that I could store the data in variables instead of files... 🤔

**Comment by Steffo99** [comment]
Both are fine, but the "hard save" would be best!

You can ignore all the cookies things and just save data to the `user://` virtual filesystem in Godot, it will handle cross-platform storage for you!
