### ISSUE TITLE
[Feature] Different colors for different areas

### ISSUE THREAD

**Issue by Steffo99** [Cookie-CHR/ASCII-quest#5]
It would be nice if changing area would also change the background (and possibly foreground?) color of the "terminal".

It can be achieved by applying a custom theme to the root element of the scene in question.

## Screenshots

![Example forest theme](https://user-images.githubusercontent.com/1540885/187551114-310dc180-b5d5-41ab-a2df-265063e49669.png "Example forest theme")

**Comment by Steffo99** [comment]
![How to set a theme](https://user-images.githubusercontent.com/1540885/187551191-9fe56ca5-ae99-4db2-8cb4-809e170aafcc.png "How to set a theme")
![How to set a font color](https://user-images.githubusercontent.com/1540885/187551245-85dea30a-b652-4028-beb2-b963afcf7e68.png "How to set a font color")
![How to set a background](https://user-images.githubusercontent.com/1540885/187551271-960b4b42-4445-4e93-81a6-4812e6ae4efd.png "How to set a background")

**Comment by Cookie-CHR** [comment]
Good idea, I'll think about it
