### ISSUE TITLE
[Design?] Allow exiting the glitched tavern without taking any action, or make it clearer that there is no going back

### ISSUE THREAD

**Issue by Steffo99** [Cookie-CHR/ASCII-quest#6]

**Comment by Steffo99** [comment]
## Screenshots

_i totally didn't mess around with the code to make a prototype for #5, i swear_

![](https://user-images.githubusercontent.com/1540885/187551843-3bf8254b-be5d-48b0-830f-742791f3ddd4.png)

![](https://user-images.githubusercontent.com/1540885/187551864-5d9b54ad-a21a-4557-b6b4-653bcf5248bf.png)

**Comment by Cookie-CHR** [comment]
Forgot to add the button, this is a simple one
