### ISSUE TITLE
[Bug] Sometimes, the "go back" actions do nothing

### ISSUE THREAD

**Issue by Steffo99** [Cookie-CHR/ASCII-quest#9]
It seems to occour in certain cases, when there's no place to go back to, such as when getting kicked out of the tavern.

## Screenshots

_again, this totally isn't me messing around with the game settings like in #5_

![](https://user-images.githubusercontent.com/1540885/187552442-e431ce3e-2c67-43e2-a036-47e007ada8df.png)

**Comment by Cookie-CHR** [comment]
Right, I should hide the button on these occasions

**Comment by Cookie-CHR** [comment]
These were actually two different bugs, both caused by me forgetting to do some stuff. Has the bug occurred on other occasions?
